Send all Slack notifications to #dm-2ndline
alphagov/digitalmarketplace-jenkins pull request #448
Opened 2021-08-19 15:40 UTC by bjgill

This is a temporary measure. Our CCS techops friends only have access to #dm-2ndline. So send all Slack notifications there so that they can see them. This will make that channel a lot more spammy, but I think that's an acceptable price to pay.

We should be able to revert this change once we've switched over to a CCS Slack (or equivalent) where we can use more than one channel.

2021-08-23 14:23 UTC, daniele-occhipinti commented
This is a good idea.
Would this be a good time to try to rename the #dm-2ndline channel to something that may be a better reflection of its use?

2021-08-24 11:15 UTC, phantas requested changes
Missing jobs:

- [x] job_definitions/create_index.yml
- [ ] job_definitions/maintenance_mode.yml

2021-08-24 13:54 UTC, bjgill commented
> This is a good idea.
> Would this be a good time to try to rename the #dm-2ndline channel to something that may be a better reflection of its use? And the answer may be that it is not.

If we carry on for a long time with just the one channel, I agree that it would be worth renaming it. However, I'm hopeful that this will be a short-lived state of affairs, so it's probably not worth renaming.

2021-08-24 14:10 UTC, bjgill commented
Good catch. Have now fixed

2021-08-25 10:44 UTC, phantas approved these changes

2021-08-25 10:58 UTC, merged